/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CrmColorSelect: typeof import('./src/components/pure/crm-color-select/index.vue')['default'];
    CrmIconFont: typeof import('./src/components/pure/crm-icon-font/index.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default'];
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default'];
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default'];
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default'];
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NIcon: typeof import('naive-ui')['NIcon'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default'];
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default'];
  }
}
