import {
  FieldDataSourceTypeEnum,
  FieldRuleEnum,
  FieldTypeEnum,
  FormDesignKeyEnum,
} from '@lib/shared/enums/formDesignEnum';
import type { CommonList } from '@lib/shared/models/common';
import type { FormDesignConfigDetailParams } from '@lib/shared/models/system/module';

import {
  addClue,
  addClueFollowPlan,
  addClueFollowRecord,
  addCustomer,
  addCustomerContact,
  addCustomerFollowPlan,
  addCustomerFollowRecord,
  addOpportunity,
  addOptFollowPlan,
  addOptFollowRecord,
  addProduct,
  ClueTransitionCustomer,
  getClue,
  getClueFollowPlan,
  getClueFollowRecord,
  getClueFormConfig,
  getClueList,
  getCluePoolList,
  getContactListUnderCustomer,
  getCustomer,
  getCustomerContact,
  getCustomerContactFormConfig,
  getCustomerContactList,
  getCustomerFollowPlan,
  getCustomerFollowPlanFormConfig,
  getCustomerFollowRecord,
  getCustomerFollowRecordFormConfig,
  getCustomerFormConfig,
  getCustomerList,
  getOpenSeaCustomer,
  getOpenSeaCustomerList,
  getOpportunityContactList,
  getOpportunityDetail,
  getOpportunityList,
  getOptFollowPlan,
  getOptFollowRecord,
  getOptFormConfig,
  getPoolClue,
  getProduct,
  getProductFormConfig,
  getProductList,
  updateClue,
  updateClueFollowPlan,
  updateClueFollowRecord,
  updateCustomer,
  updateCustomerContact,
  updateCustomerFollowPlan,
  updateCustomerFollowRecord,
  updateOpportunity,
  updateOptFollowPlan,
  updateOptFollowRecord,
  updateProduct,
} from '@/api/modules';

import type { FormCreateField, FormCreateFieldRule, FormDetail } from './types';

export const multipleValueTypeList = [
  FieldTypeEnum.MEMBER_MULTIPLE,
  FieldTypeEnum.DEPARTMENT_MULTIPLE,
  FieldTypeEnum.DATA_SOURCE_MULTIPLE,
  FieldTypeEnum.CHECKBOX,
  FieldTypeEnum.SELECT_MULTIPLE,
  FieldTypeEnum.INPUT_MULTIPLE,
];

export const inputDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.INPUT,
  name: 'crmFormDesign.input',
  icon: 'iconicon_single_line_text',
  fieldWidth: 1,
  showLabel: true,
  defaultValue: '',
  description: '',
  readable: true,
  editable: true,
  rules: [],
};

export const textareaDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.TEXTAREA,
  icon: 'iconicon_multiline',
  name: 'crmFormDesign.textarea',
  fieldWidth: 1,
  showLabel: true,
  defaultValue: '',
  description: '',
  readable: true,
  editable: true,
  rules: [],
};

export const inputNumberDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.INPUT_NUMBER,
  icon: 'iconicon_hashtag_key',
  name: 'crmFormDesign.inputNumber',
  fieldWidth: 1,
  showLabel: true,
  defaultValue: null,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  numberFormat: 'number',
  decimalPlaces: false,
  precision: 0,
  showThousandsSeparator: false,
};

export const dateTimeDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.DATE_TIME,
  icon: 'iconicon_calendar1',
  name: 'crmFormDesign.dateTime',
  fieldWidth: 1,
  showLabel: true,
  defaultValue: null,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  dateType: 'datetime',
};

export const radioDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.RADIO,
  icon: 'iconicon_radio',
  name: 'crmFormDesign.radio',
  fieldWidth: 1,
  showLabel: true,
  defaultValue: '',
  description: '',
  options: [],
  readable: true,
  editable: true,
  rules: [],
  direction: 'vertical',
};

export const checkboxDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.CHECKBOX,
  icon: 'icona-icon_collectbeifen12',
  name: 'crmFormDesign.checkbox',
  fieldWidth: 1,
  showLabel: true,
  defaultValue: [],
  description: '',
  options: [],
  readable: true,
  editable: true,
  rules: [],
  direction: 'vertical',
};

export const selectDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.SELECT,
  icon: 'iconicon_pull_down_single_choice',
  name: 'crmFormDesign.select',
  fieldWidth: 1,
  showLabel: true,
  options: [],
  defaultValue: '',
  description: '',
  readable: true,
  editable: true,
  rules: [],
  multiple: false,
};

export const selectMultipleDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.SELECT_MULTIPLE,
  icon: 'iconicon_pull_down_single_choice',
  name: 'crmFormDesign.selectMultiple',
  fieldWidth: 1,
  showLabel: true,
  options: [],
  defaultValue: [],
  description: '',
  readable: true,
  editable: true,
  rules: [],
  multiple: false,
};

export const memberDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.MEMBER,
  icon: 'iconicon_member_single_choice',
  name: 'crmFormDesign.memberSelect',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  defaultValue: [],
  initialOptions: [],
  multiple: false,
};

export const memberMultipleDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.MEMBER_MULTIPLE,
  icon: 'iconicon_member_single_choice',
  name: 'crmFormDesign.memberSelectMultiple',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  defaultValue: [],
  initialOptions: [],
  multiple: false,
};

export const departmentDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.DEPARTMENT,
  icon: 'iconicon_department_single_choice',
  name: 'crmFormDesign.departmentSelect',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  defaultValue: [],
  initialOptions: [],
  multiple: false,
};

export const departmentMultipleDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.DEPARTMENT_MULTIPLE,
  icon: 'iconicon_department_single_choice',
  name: 'crmFormDesign.departmentSelectMultiple',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  defaultValue: [],
  initialOptions: [],
  multiple: false,
};

export const dividerDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.DIVIDER,
  icon: 'iconicon_dividing_line',
  name: 'crmFormDesign.divider',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  dividerClass: 'divider--normal',
  dividerColor: '#edf0f1',
  titleColor: '#323535',
};

export const tagInputDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.INPUT_MULTIPLE,
  icon: 'iconicon_books',
  name: 'common.tag',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  defaultValue: [],
};

export const basicFields: FormCreateField[] = [
  inputDefaultFieldConfig,
  textareaDefaultFieldConfig,
  inputNumberDefaultFieldConfig,
  dateTimeDefaultFieldConfig,
  radioDefaultFieldConfig,
  checkboxDefaultFieldConfig,
  selectDefaultFieldConfig,
  selectMultipleDefaultFieldConfig,
  memberDefaultFieldConfig,
  memberMultipleDefaultFieldConfig,
  departmentDefaultFieldConfig,
  departmentMultipleDefaultFieldConfig,
  dividerDefaultFieldConfig,
  tagInputDefaultFieldConfig,
];

export const pictureDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.PICTURE,
  icon: 'iconicon_picture',
  name: 'crmFormDesign.picture',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  defaultValue: [],
  readable: true,
  editable: true,
  rules: [],
  uploadLimit: 10,
  uploadSizeLimit: 20,
  pictureShowType: 'card',
  uploadLimitEnable: false,
  uploadSizeLimitEnable: false,
};

export const locationDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.LOCATION,
  icon: 'iconicon_map',
  name: 'crmFormDesign.location',
  fieldWidth: 1,
  showLabel: true,
  defaultValue: '',
  description: '',
  readable: true,
  editable: true,
  rules: [],
  locationType: 'PCD',
};

export const phoneDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.PHONE,
  icon: 'iconicon_phone',
  name: 'crmFormDesign.phone',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  defaultValue: null,
  readable: true,
  editable: true,
  rules: [],
};

export const dataSourceDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.DATA_SOURCE,
  icon: 'iconicon_select_data',
  name: 'crmFormDesign.dataSource',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  multiple: false,
  defaultValue: [],
  initialOptions: [],
  dataSourceType: FieldDataSourceTypeEnum.CUSTOMER,
};

export const dataSourceMultipleDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.DATA_SOURCE_MULTIPLE,
  icon: 'iconicon_select_data',
  name: 'crmFormDesign.dataSourceMultiple',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: true,
  rules: [],
  multiple: false,
  defaultValue: [],
  initialOptions: [],
  dataSourceType: FieldDataSourceTypeEnum.CUSTOMER,
};

export const serialNumberDefaultFieldConfig: FormCreateField = {
  id: '',
  type: FieldTypeEnum.SERIAL_NUMBER,
  icon: 'iconicon_serial_number',
  name: 'crmFormDesign.serialNumber',
  fieldWidth: 1,
  showLabel: true,
  description: '',
  readable: true,
  editable: false,
  rules: [],
  serialNumberRules: ['Opp', '-', 'YYMM', '-', 6],
};

export const advancedFields: FormCreateField[] = [
  pictureDefaultFieldConfig,
  locationDefaultFieldConfig,
  phoneDefaultFieldConfig,
  dataSourceDefaultFieldConfig,
  dataSourceMultipleDefaultFieldConfig,
  serialNumberDefaultFieldConfig,
];

export const rules: FormCreateFieldRule[] = [
  {
    key: FieldRuleEnum.REQUIRED,
    required: true,
    message: 'common.notNull',
    label: 'common.required',
    trigger: 'change',
  },
  {
    key: FieldRuleEnum.UNIQUE,
    message: 'common.valueExists',
    label: 'common.onlyOne',
    validator: () => true, // 由后台验证
  },
];

export const showRulesMap: Record<FieldTypeEnum, FieldRuleEnum[]> = {
  [FieldTypeEnum.INPUT]: [FieldRuleEnum.REQUIRED, FieldRuleEnum.UNIQUE],
  [FieldTypeEnum.TEXTAREA]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.INPUT_NUMBER]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.DATE_TIME]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.RADIO]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.CHECKBOX]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.SELECT]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.SELECT_MULTIPLE]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.MEMBER]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.MEMBER_MULTIPLE]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.DEPARTMENT]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.DEPARTMENT_MULTIPLE]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.DIVIDER]: [],
  [FieldTypeEnum.USER_TAG_SELECTOR]: [],
  [FieldTypeEnum.USER_SELECT]: [],
  [FieldTypeEnum.TIME_RANGE_PICKER]: [],
  [FieldTypeEnum.TREE_SELECT]: [],
  [FieldTypeEnum.INPUT_MULTIPLE]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.PICTURE]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.LOCATION]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.PHONE]: [FieldRuleEnum.REQUIRED, FieldRuleEnum.UNIQUE],
  [FieldTypeEnum.DATA_SOURCE]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.DATA_SOURCE_MULTIPLE]: [FieldRuleEnum.REQUIRED],
  [FieldTypeEnum.SERIAL_NUMBER]: [],
};

export const getFormConfigApiMap: Record<FormDesignKeyEnum, () => Promise<FormDesignConfigDetailParams>> = {
  [FormDesignKeyEnum.CUSTOMER]: getCustomerFormConfig,
  [FormDesignKeyEnum.BUSINESS]: getOptFormConfig,
  [FormDesignKeyEnum.CONTACT]: getCustomerContactFormConfig,
  [FormDesignKeyEnum.CUSTOMER_CONTACT]: getCustomerContactFormConfig,
  [FormDesignKeyEnum.FOLLOW_PLAN_CUSTOMER]: getCustomerFollowPlanFormConfig,
  [FormDesignKeyEnum.FOLLOW_RECORD_CUSTOMER]: getCustomerFollowRecordFormConfig,
  [FormDesignKeyEnum.FOLLOW_PLAN_CLUE]: getCustomerFollowPlanFormConfig,
  [FormDesignKeyEnum.FOLLOW_RECORD_CLUE]: getCustomerFollowRecordFormConfig,
  [FormDesignKeyEnum.FOLLOW_PLAN_BUSINESS]: getCustomerFollowPlanFormConfig,
  [FormDesignKeyEnum.FOLLOW_RECORD_BUSINESS]: getCustomerFollowRecordFormConfig,
  [FormDesignKeyEnum.CLUE]: getClueFormConfig,
  [FormDesignKeyEnum.CLUE_TRANSITION_CUSTOMER]: getCustomerFormConfig,
  [FormDesignKeyEnum.CLUE_POOL]: getClueFormConfig,
  [FormDesignKeyEnum.PRODUCT]: getProductFormConfig,
  [FormDesignKeyEnum.CUSTOMER_OPEN_SEA]: getCustomerFormConfig,
  [FormDesignKeyEnum.BUSINESS_CONTACT]: getCustomerContactFormConfig,
};

export const createFormApi: Record<FormDesignKeyEnum, (data: any) => Promise<any>> = {
  [FormDesignKeyEnum.CUSTOMER]: addCustomer,
  [FormDesignKeyEnum.BUSINESS]: addOpportunity,
  [FormDesignKeyEnum.CONTACT]: addCustomerContact,
  [FormDesignKeyEnum.CUSTOMER_CONTACT]: addCustomerContact,
  [FormDesignKeyEnum.BUSINESS_CONTACT]: addCustomerContact,
  [FormDesignKeyEnum.FOLLOW_PLAN_CUSTOMER]: addCustomerFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_CUSTOMER]: addCustomerFollowRecord,
  [FormDesignKeyEnum.FOLLOW_PLAN_CLUE]: addClueFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_CLUE]: addClueFollowRecord,
  [FormDesignKeyEnum.FOLLOW_PLAN_BUSINESS]: addOptFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_BUSINESS]: addOptFollowRecord,
  [FormDesignKeyEnum.CLUE]: addClue,
  [FormDesignKeyEnum.CLUE_TRANSITION_CUSTOMER]: ClueTransitionCustomer,
  [FormDesignKeyEnum.CLUE_POOL]: async () => ({}),
  [FormDesignKeyEnum.PRODUCT]: addProduct,
  [FormDesignKeyEnum.CUSTOMER_OPEN_SEA]: async () => ({}), // 公海无添加
};

export const updateFormApi: Record<FormDesignKeyEnum, (data: any) => Promise<any>> = {
  [FormDesignKeyEnum.CUSTOMER]: updateCustomer,
  [FormDesignKeyEnum.BUSINESS]: updateOpportunity,
  [FormDesignKeyEnum.CONTACT]: updateCustomerContact,
  [FormDesignKeyEnum.CUSTOMER_CONTACT]: updateCustomerContact,
  [FormDesignKeyEnum.BUSINESS_CONTACT]: updateCustomerContact,
  [FormDesignKeyEnum.FOLLOW_PLAN_CUSTOMER]: updateCustomerFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_CUSTOMER]: updateCustomerFollowRecord,
  [FormDesignKeyEnum.FOLLOW_PLAN_CLUE]: updateClueFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_CLUE]: updateClueFollowRecord,
  [FormDesignKeyEnum.FOLLOW_PLAN_BUSINESS]: updateOptFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_BUSINESS]: updateOptFollowRecord,
  [FormDesignKeyEnum.CLUE]: updateClue,
  [FormDesignKeyEnum.CLUE_TRANSITION_CUSTOMER]: async () => ({}),
  [FormDesignKeyEnum.CLUE_POOL]: async () => ({}),
  [FormDesignKeyEnum.PRODUCT]: updateProduct,
  [FormDesignKeyEnum.CUSTOMER_OPEN_SEA]: async () => ({}), // 公海无更新
};

export const getFormDetailApiMap: Partial<Record<FormDesignKeyEnum, (id: string) => Promise<FormDetail>>> = {
  [FormDesignKeyEnum.CUSTOMER]: getCustomer,
  [FormDesignKeyEnum.BUSINESS]: getOpportunityDetail,
  [FormDesignKeyEnum.CONTACT]: getCustomerContact,
  [FormDesignKeyEnum.CUSTOMER_CONTACT]: getCustomerContact,
  [FormDesignKeyEnum.FOLLOW_PLAN_CUSTOMER]: getCustomerFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_CUSTOMER]: getCustomerFollowRecord,
  [FormDesignKeyEnum.FOLLOW_PLAN_CLUE]: getClueFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_CLUE]: getClueFollowRecord,
  [FormDesignKeyEnum.FOLLOW_PLAN_BUSINESS]: getOptFollowPlan,
  [FormDesignKeyEnum.FOLLOW_RECORD_BUSINESS]: getOptFollowRecord,
  [FormDesignKeyEnum.CLUE]: getClue,
  [FormDesignKeyEnum.CLUE_POOL]: getPoolClue,
  [FormDesignKeyEnum.PRODUCT]: getProduct,
  [FormDesignKeyEnum.CUSTOMER_OPEN_SEA]: getOpenSeaCustomer,
};

export const getFormListApiMap: Partial<Record<FormDesignKeyEnum, (data: any) => Promise<CommonList<any>>>> = {
  [FormDesignKeyEnum.CUSTOMER]: getCustomerList,
  [FormDesignKeyEnum.BUSINESS]: getOpportunityList,
  [FormDesignKeyEnum.CONTACT]: getCustomerContactList,
  [FormDesignKeyEnum.CUSTOMER_CONTACT]: getContactListUnderCustomer,
  [FormDesignKeyEnum.CLUE]: getClueList,
  [FormDesignKeyEnum.CLUE_POOL]: getCluePoolList,
  [FormDesignKeyEnum.PRODUCT]: getProductList,
  [FormDesignKeyEnum.CUSTOMER_OPEN_SEA]: getOpenSeaCustomerList,
  [FormDesignKeyEnum.BUSINESS_CONTACT]: getOpportunityContactList,
};
