export enum FieldTypeEnum {
  INPUT = 'INPUT',
  TEXTAREA = 'TEXTAREA',
  INPUT_NUMBER = 'INPUT_NUMBER',
  DATE_TIME = 'DATE_TIME',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
  SELECT = 'SELECT',
  USER_TAG_SELECTOR = 'USER_TAG_SELECTOR',
  SELECT_SINGLE = 'SELECT_SINGLE',
  SELECT_MULTIPLE = 'SELECT_MULTIPLE',
  MEMBER_SINGLE = 'MEMBER_SINGLE',
  MEMBER_MULTIPLE = 'MEMBER_MULTIPLE',
  DEPARTMENT_SINGLE = 'DEPARTMENT_SINGLE',
  DEPARTMENT_MULTIPLE = 'DEPARTMENT_MULTIPLE',
  DIVIDER = 'DIVIDER',
  // 高级字段
  PICTURE = 'PICTURE',
  LOCATION = 'LOCATION',
  PHONE = 'PHONE',
}

export enum FieldRuleEnum {
  REQUIRED = 'required',
  UNIQUE = 'unique',
  NUMBER_RANGE = 'numberRange',
}
