export const GetCustomerFormConfigUrl = '/customer/module/form'; // 获取客户表单配置
export const UpdateCustomerUrl = '/customer/update'; // 更新客户
export const GetCustomerListUrl = '/customer/page'; // 分页查询客户
export const AddCustomerUrl = '/customer/add'; // 添加客户
export const GetCustomerUrl = '/customer/get'; // 获取客户详情
export const DeleteCustomerUrl = '/customer/delete'; // 删除客户
export const BatchDeleteCustomerUrl = '/customer/batch/delete'; // 批量删除客户
export const BatchTransferCustomerUrl = '/customer/batch/transfer'; // 批量转移客户
export const BatchMoveCustomerUrl = '/customer/batch/to-pool'; // 批量移入公海
export const MoveToCustomerUrl = '/customer/to-pool'; // 移入公海
export const UpdateCustomerFollowRecordUrl = '/customer/follow/record/update'; // 更新跟进记录
export const GetCustomerFollowRecordListUrl = '/customer/follow/record/page'; // 获取跟进记录列表
export const AddCustomerFollowRecordUrl = '/customer/follow/record/add'; // 添加跟进记录
export const DeleteCustomerFollowRecordUrl = '/customer/follow/record/delete'; // 删除跟进记录
export const GetCustomerFollowRecordUrl = '/customer/follow/record/get'; // 获取跟进记录详情
export const GetCustomerFollowRecordFormConfigUrl = '/follow/record/module/form'; // 获取跟进记录表单配置
export const UpdateCustomerFollowPlanUrl = '/customer/follow/plan/update'; // 更新跟进计划
export const GetCustomerFollowPlanListUrl = '/customer/follow/plan/page'; // 获取跟进计划列表
export const AddCustomerFollowPlanUrl = '/customer/follow/plan/add'; // 添加跟进计划
export const DeleteCustomerFollowPlanUrl = '/customer/follow/plan/delete'; // 删除跟进计划
export const GetCustomerFollowPlanFormConfigUrl = '/follow/plan/module/form'; // 获取跟进计划表单配置
export const GetCustomerFollowPlanUrl = '/customer/follow/plan/get'; // 获取跟进记录详情
export const UpdateCustomerContactUrl = '/customer/contact/update'; // 更新客户联系人
export const GetCustomerContactListUrl = '/customer/contact/page'; // 获取客户联系人列表
export const DisableCustomerContactUrl = '/customer/contact/disable'; // 禁用客户联系人
export const AddCustomerContactUrl = '/customer/contact/add'; // 添加客户联系人
export const GetCustomerContactFormConfigUrl = '/customer/contact/module/form'; // 获取客户联系人表单配置
export const GetCustomerContactUrl = '/customer/contact/get'; // 获取客户联系人详情
export const EnableCustomerContactUrl = '/customer/contact/enable'; // 启用客户联系人
export const DeleteCustomerContactUrl = '/customer/contact/delete'; // 删除客户联系人
export const CheckOpportunityContactUrl = '/customer/contact/opportunity/check'; // 是否绑定商机
export const ContactListUnderCustomerUrl = '/customer/contact/list'; // 客户下的联系人列表
export const UpdateCustomerOpenSeaUrl = '/customer-pool/update'; // 编辑公海
export const GetCustomerOpenSeaListUrl = '/customer-pool/page'; // 公海列表
export const AddCustomerOpenSeaUrl = '/customer-pool/add'; // 添加公海
export const SwitchCustomerOpenSeaUrl = '/customer-pool/switch'; // 启用/禁用公海
export const IsCustomerOpenSeaNoPickUrl = '/customer-pool/no-pick'; // 公海是否存在未领取线索
export const DeleteCustomerOpenSeaUrl = '/customer-pool/delete'; // 删除公海
export const GetOpenSeaCustomerListUrl = '/pool/customer/page'; // 公海客户列表
export const PickOpenSeaCustomerUrl = '/pool/customer/pick'; // 领取公海客户
export const BatchPickOpenSeaCustomerUrl = '/pool/customer/batch-pick'; // 批量领取公海客户
export const BatchDeleteOpenSeaCustomerUrl = '/pool/customer/batch-delete'; // 批量删除公海客户
export const BatchAssignOpenSeaCustomerUrl = '/pool/customer/batch-assign'; // 批量分配公海客户
export const AssignOpenSeaCustomerUrl = '/pool/customer/assign'; // 分配公海客户
export const GetOpenSeaOptionsUrl = '/pool/customer/options'; // 获取公海选项
export const DeleteOpenSeaCustomerUrl = '/pool/customer/delete'; // 删除公海客户
export const GetOpenSeaCustomerUrl = '/pool/customer/get'; // 获取公海客户详情
export const CancelCustomerFollowPlanUrl = '/customer/follow/plan/cancel'; // 取消客户跟进计划
export const GetCustomerHeaderListUrl = '/customer/owner/history/list'; // 客户负责人记录列表
export const SaveCustomerRelationUrl = '/customer/relation/save'; // 保存客户关系
export const GetCustomerRelationListUrl = '/customer/relation/list'; // 获取客户关系列表
export const UpdateCustomerRelationItemUrl = '/customer/relation/update'; // 更新单条客户关系
export const AddCustomerRelationItemUrl = '/customer/relation/add'; // 添加单条客户关系
export const DeleteCustomerRelationItemUrl = '/customer/relation/delete'; // 删除单条客户关系
export const UpdateCustomerCollaborationUrl = '/customer/collaboration/update'; // 更新协作成员
export const BatchDeleteCustomerCollaborationUrl = '/customer/collaboration/batch/delete'; // 批量删除协作成员
export const AddCustomerCollaborationUrl = '/customer/collaboration/add'; // 添加协作成员
export const GetCustomerCollaborationListUrl = '/customer/collaboration/list'; // 获取协作成员列表
export const DeleteCustomerCollaborationUrl = '/customer/collaboration/delete'; // 删除协作成员
export const GetCustomerOptionsUrl = '/customer/option'; // 获取客户选项列表
export const GetCustomerOpenSeaFollowRecordListUrl = '/customer/follow/record/pool/page'; // 获取客户公海池跟进记录列表
export const GetCustomerTabUrl = '/customer/tab'; // 客户tab显隐
export const GetCustomerContactTabUrl = '/customer/contact/tab'; // 客户联系人tab显隐
export const UpdateCustomerFollowPlanStatusUrl = '/customer/follow/plan/status/update'; // 更新客户跟进计划状态
export const GetCustomerOpportunityListUrl = '/customer/opportunity/page'; // 客户商机列表
export const ExportCustomerAllUrl = '/customer/export-all'; // 导出所有客户
export const ExportCustomerSelectedUrl = '/customer/export-select'; // 导出选中客户
export const GetGlobalCustomerListUrl = '/global/search/customer'; // 全局搜索分页查询客户
export const GetGlobalOpenSeaCustomerListUrl = '/global/search/customer-pool'; // 全局搜索公海客户列表
export const GetGlobalCustomerContactListUrl = '/global/search/contact'; // 全局搜索获取客户联系人列表

// 视图
export const GetCustomerViewDetailUrl = '/customer/view/detail';
export const GetCustomerViewListUrl = '/customer/view/list';
export const AddCustomerViewUrl = '/customer/view/add';
export const UpdateCustomerViewUrl = '/customer/view/update';
export const DeleteCustomerViewUrl = '/customer/view/delete';
export const FixedCustomerViewUrl = '/customer/view/fixed';
export const EnableCustomerViewUrl = '/customer/view/enable';
export const DragCustomerViewUrl = '/customer/view/edit/pos';

export const GetContactViewDetailUrl = '/customer/contact/view/detail';
export const GetContactViewListUrl = '/customer/contact/view/list';
export const AddContactViewUrl = '/customer/contact/view/add';
export const UpdateContactViewUrl = '/customer/contact/view/update';
export const DeleteContactViewUrl = '/customer/contact/view/delete';
export const FixedContactViewUrl = '/customer/contact/view/fixed';
export const EnableContactViewUrl = '/customer/contact/view/enable';
export const DragContactViewUrl = '/customer/contact/view/edit/pos';
