/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Create: typeof import('./src/components/business/crm-contact-list/create.vue')['default'];
    CrmContactList: typeof import('./src/components/business/crm-contact-list/index.vue')['default'];
    CrmDescription: typeof import('./src/components/pure/crm-description/index.vue')['default'];
    CrmFormCreate: typeof import('./src/components/business/crm-form-create/index.vue')['default'];
    CrmHeaderList: typeof import('./src/components/business/crm-header-list/index.vue')['default'];
    CrmIconFont: typeof import('./src/components/pure/crm-icon-font/index.vue')['default'];
    CrmList: typeof import('./src/components/pure/crm-list/index.vue')['default'];
    CrmListCommonItem: typeof import('./src/components/pure/crm-list-common-item/index.vue')['default'];
    CrmMessageItem: typeof import('./src/components/business/crm-message-item/index.vue')['default'];
    CrmPageHeader: typeof import('./src/components/pure/crm-page-header/index.vue')['default'];
    CrmPageWrapper: typeof import('./src/components/pure/crm-page-wrapper/index.vue')['default'];
    CrmPasswordInput: typeof import('./src/components/pure/crm-password-input/index.vue')['default'];
    CrmSelectList: typeof import('./src/components/business/crm-select-list/index.vue')['default'];
    CrmTag: typeof import('./src/components/pure/crm-tag/index.vue')['default'];
    CrmTextButton: typeof import('./src/components/pure/crm-text-button/index.vue')['default'];
    DataSource: typeof import('./src/components/business/crm-form-create/components/advanced/dataSource.vue')['default'];
    DatePicker: typeof import('./src/components/business/crm-form-create/components/basic/datePicker.vue')['default'];
    Detail: typeof import('./src/components/business/crm-contact-list/detail.vue')['default'];
    FollowDetail: typeof import('./src/components/business/crm-follow-list/followDetail.vue')['default'];
    FollowPlan: typeof import('./src/components/business/crm-follow-list/followPlan.vue')['default'];
    FollowPlanCreate: typeof import('./src/components/business/crm-follow-list/followPlanCreate.vue')['default'];
    FollowRecord: typeof import('./src/components/business/crm-follow-list/followRecord.vue')['default'];
    Input: typeof import('./src/components/business/crm-form-create/components/basic/input.vue')['default'];
    ListItem: typeof import('./src/components/business/crm-follow-list/components/listItem.vue')['default'];
    MultiplePick: typeof import('./src/components/business/crm-form-create/components/basic/multiplePick.vue')['default'];
    Phone: typeof import('./src/components/business/crm-form-create/components/advanced/phone.vue')['default'];
    Pick: typeof import('./src/components/business/crm-form-create/components/basic/pick.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SingleText: typeof import('./src/components/business/crm-form-create/components/basic/singleText.vue')['default'];
    Textarea: typeof import('./src/components/business/crm-form-create/components/basic/textarea.vue')['default'];
    VanBadge: typeof import('vant/es')['Badge'];
    VanButton: typeof import('vant/es')['Button'];
    VanCell: typeof import('vant/es')['Cell'];
    VanCellGroup: typeof import('vant/es')['CellGroup'];
    VanCheckbox: typeof import('vant/es')['Checkbox'];
    VanDatePicker: typeof import('vant/es')['DatePicker'];
    VanDivider: typeof import('vant/es')['Divider'];
    VanEmpty: typeof import('vant/es')['Empty'];
    VanField: typeof import('vant/es')['Field'];
    VanForm: typeof import('vant/es')['Form'];
    VanIcon: typeof import('vant/es')['Icon'];
    VanImage: typeof import('vant/es')['Image'];
    VanList: typeof import('vant/es')['List'];
    VanNavBar: typeof import('vant/es')['NavBar'];
    VanPicker: typeof import('vant/es')['Picker'];
    VanPickerGroup: typeof import('vant/es')['PickerGroup'];
    VanPopup: typeof import('vant/es')['Popup'];
    VanPullRefresh: typeof import('vant/es')['PullRefresh'];
    VanRadio: typeof import('vant/es')['Radio'];
    VanRadioGroup: typeof import('vant/es')['RadioGroup'];
    VanSearch: typeof import('vant/es')['Search'];
    VanTab: typeof import('vant/es')['Tab'];
    VanTabbar: typeof import('vant/es')['Tabbar'];
    VanTabbarItem: typeof import('vant/es')['TabbarItem'];
    VanTabs: typeof import('vant/es')['Tabs'];
    VanTag: typeof import('vant/es')['Tag'];
    VanTimePicker: typeof import('vant/es')['TimePicker'];
  }
}
