/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Create: typeof import('./src/components/business/crm-contact-list/create.vue')['default']
    CrmContactList: typeof import('./src/components/business/crm-contact-list/index.vue')['default']
    CrmDescription: typeof import('./src/components/pure/crm-description/index.vue')['default']
    CrmFormCreate: typeof import('./src/components/business/crm-form-create/index.vue')['default']
    CrmHeaderList: typeof import('./src/components/business/crm-header-list/index.vue')['default']
    CrmIconFont: typeof import('./src/components/pure/crm-icon-font/index.vue')['default']
    CrmList: typeof import('./src/components/pure/crm-list/index.vue')['default']
    CrmListCommonItem: typeof import('./src/components/pure/crm-list-common-item/index.vue')['default']
    CrmPageHeader: typeof import('./src/components/pure/crm-page-header/index.vue')['default']
    CrmPageWrapper: typeof import('./src/components/pure/crm-page-wrapper/index.vue')['default']
    CrmTag: typeof import('./src/components/pure/crm-tag/index.vue')['default']
    CrmTextButton: typeof import('./src/components/pure/crm-text-button/index.vue')['default']
    Detail: typeof import('./src/components/business/crm-contact-list/detail.vue')['default']
    FollowDetail: typeof import('./src/components/business/crm-follow-list/followDetail.vue')['default']
    FollowPlan: typeof import('./src/components/business/crm-follow-list/followPlan.vue')['default']
    FollowPlanCreate: typeof import('./src/components/business/crm-follow-list/followPlanCreate.vue')['default']
    FollowRecord: typeof import('./src/components/business/crm-follow-list/followRecord.vue')['default']
    ListItem: typeof import('./src/components/business/crm-follow-list/components/listItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
